apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
    service:
      annotations:
        svccontroller.k3s.cattle.io/tolerations: '[{"key":"dedicated","operator":"Equal","value":"pi","effect":"NoSchedule"}]'
