apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-verify-script
  namespace: kube-system
  annotations:
    argocd.argoproj.io/hook: PostSync
data:
{{- (.Files.Glob "scripts/*").AsConfig | nindent 2 }}
